export * from './icon';
export * from './typography';
export * from './layout';
export * from './other';
export * from './button';
export * from './carousel';
export * from './popup';
export * from './tooltip';
export * from './loading';

export const COLOR_ARRAY = [
  'white',
  'gray',
  'primary',
  'orangeColor9',
  'orangeColor8',
  'orangeColor7',
  'orangeColor6',
  'orangeColor5',
  'orangeColor4',
  'orangeColor3',
  'orangeColor2',
  'orangeColor1',
  'blueColor9',
  'blueColor8',
  'blueColor7',
  'blueColor6',
  'blueColor5',
  'blueColor4',
  'blueColor3',
  'blueColor2',
  'blueColor1',
  'greenColor9',
  'greenColor8',
  'greenColor7',
  'greenColor6',
  'greenColor5',
  'greenColor4',
  'greenColor3',
  'greenColor2',
  'greenColor1',
  'crimsonColor9',
  'crimsonColor8',
  'crimsonColor7',
  'crimsonColor6',
  'crimsonColor5',
  'crimsonColor4',
  'crimsonColor3',
  'crimsonColor2',
  'crimsonColor1',
  'grayColor',
  'gray85Color',
  'gray70Color',
  'gray60Color',
  'gray45Color',
  'gray30Color',
  'gray15Color',
  'gray10Color',
  'gray4Color',
  'otherJavaColor',
  'otherBrightTurquoiseColor',
  'otherElectricViolet',
  'otherRoyalBlueColor',
  'otherRedColor',
  'orange9',
  'orange8',
  'orange7',
  'orange6',
  'orange5',
  'orange4',
  'orange3',
  'orange2',
  'orange1',
  'blue9',
  'blue8',
  'blue7',
  'blue6',
  'blue5',
  'blue4',
  'blue3',
  'blue2',
  'blue1',
  'green9',
  'green8',
  'green7',
  'green6',
  'green5',
  'green4',
  'green3',
  'green2',
  'green1',
  'crimson9',
  'crimson8',
  'crimson7',
  'crimson6',
  'crimson5',
  'crimson4',
  'crimson3',
  'crimson2',
  'crimson1',
  'corn9',
  'corn8',
  'corn7',
  'corn6',
  'corn5',
  'corn4',
  'corn3',
  'corn2',
  'corn1',
  'gray',
  'gray85',
  'gray70',
  'gray60',
  'gray45',
  'gray30',
  'gray15',
  'gray10',
  'gray4',
  'otherRed'
] as const;

export const GRID_VALUES = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24
] as const;
